default_language_version:
  python: python3

default_stages:
  - commit

repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [ python ]
        require_serial: true
      - id: ruff
        name: ruff
        entry: poetry run ruff
        language: system
        types: [ python ]
        require_serial: true
        args: [ --fix, --exit-non-zero-on-fix ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: \.noeof\. # Some tests require no EOF
      - id: fix-encoding-pragma
        args: [ "--remove" ]
      - id: mixed-line-ending
        args: [ "--fix=lf" ]
      - id: trailing-whitespace
  - repo: https://github.com/python-poetry/poetry
    rev: '1.5.1'
    hooks:
      - id: poetry-export
        args:
          - -f
          - requirements.txt
          - -o
          - requirements.txt
          - --without-hashes
